config/routes.rb
Icards::Application.routes.draw do
  resources :index_cards

  resources :topics
  match 'index_cards/:id/back' => 'index_cards#back', :as => :show_back
  root :to => 'topics#index'
  

end

app/models/index_card.rb
class IndexCard < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_cards_controller.rb
class IndexCardsController < ApplicationController
  # GET /index_cards
  # GET /index_cards.json
  def index
    @index_cards = IndexCard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @index_cards }
    end
  end

  # GET /index_cards/1
  # GET /index_cards/1.json
  def show
    @index_card = IndexCard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @index_card }
    end
  end
  def back
    @index_card = IndexCard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @index_card }
    end
  end

  # GET /index_cards/new
  # GET /index_cards/new.json
  def new
    @index_card = IndexCard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @index_card }
    end
  end

  # GET /index_cards/1/edit
  def edit
    @index_card = IndexCard.find(params[:id])
  end

  # POST /index_cards
  # POST /index_cards.json
  def create
    @index_card = IndexCard.new(params[:index_card])

    respond_to do |format|
      if @index_card.save
        format.html { redirect_to @index_card, notice: 'Index card was successfully created.' }
        format.json { render json: @index_card, status: :created, location: @index_card }
      else
        format.html { render action: "new" }
        format.json { render json: @index_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /index_cards/1
  # PUT /index_cards/1.json
  def update
    @index_card = IndexCard.find(params[:id])

    respond_to do |format|
      if @index_card.update_attributes(params[:index_card])
        format.html { redirect_to @index_card, notice: 'Index card was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @index_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /index_cards/1
  # DELETE /index_cards/1.json
  def destroy
    @index_card = IndexCard.find(params[:id])
    @index_card.destroy

    respond_to do |format|
      format.html { redirect_to index_cards_url }
      format.json { head :ok }
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_cards_helper.rb
module IndexCardsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/index_cards/_form.html.erb
<%= form_for(@index_card) do |f| %>
  <% if @index_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@index_card.errors.count, "error") %> prohibited this index_card from being saved:</h2>

      <ul>
      <% @index_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
 <div class="field">
    <%= f.label :topic_id %><br />
    <%= f.number_field :topic_id %>
  </div>

  <div class="field">
    <%= f.label :front %><br />
    <%= f.text_field :front %>
  </div>
  <div class="field">
    <%= f.label :back %><br />
    <%= f.text_field :back %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/index_cards/back.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @index_card.title %>
</p>

<p>
  <b>Front:</b>
  <%= @index_card.front %>
</p>

<p>
  <b>Back:</b>
  <%= @index_card.back %>
</p>


<%= link_to 'Edit', edit_index_card_path(@index_card) %> |
<%= link_to 'Back', index_cards_path %>

app/views/index_cards/edit.html.erb
<h1>Editing index_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @index_card %> |
<%= link_to 'Back', index_cards_path %>

app/views/index_cards/index.html.erb
<h1>Listing index_cards</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Front</th>
    <th>Back</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @index_cards.each do |index_card| %>
  <tr>
    <td><%= index_card.title %></td>
    <td><%= index_card.front %></td>
    <td><%= index_card.back %></td>
    <td><%= link_to 'Show', index_card %></td>
    <td><%= link_to 'Edit', edit_index_card_path(index_card) %></td>
    <td><%= link_to 'Destroy', index_card, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Index card', new_index_card_path %>

app/views/index_cards/new.html.erb
<h1>New index_card</h1>

<%= render 'form' %>

<%= link_to 'Back', index_cards_path %>

app/views/index_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @index_card.title %>
</p>

<p>
  <b>Front:</b>
  <%= @index_card.front %>
</p>

<p>
  <b>Back:</b>
  <%= @index_card.back %>
</p>


<%= link_to 'Edit', edit_index_card_path(@index_card) %> |
<%= link_to 'Back', index_cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Icards</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @topic.title %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>